### ISSUE TITLE
如果promise reject的时候会产生Uncaught错误

### ISSUE THREAD

**Issue by alianrock** [kpaxqin/redux-action-tools#2]
运行todo example，falied的时候会
index.js:7 Uncaught (in promise) Error: Ops, async operation failed
    at index.js:7

**Comment by kpaxqin** [comment]
Actually those error message is not a problem, it won't block anything, just a warning for uncaught failed promise.

You see this error becuz when dispatching an async action, it actually *returns* another promise -- which will be fulfilled when async action succeed and rejected if async action failed.

We do it for support `chainable action`: 

```js
class Todo extends Component{
  handleClick() {
     actionFoo().then(/* do something here */)
  }
}
```

`chainable action` is quite handy in some cases, but in most cases we just send action without `then` or `catch` followed，so if the async behavior failed, the promise returned by action call will become "uncaught failed promise" and display error message you saw.

You can simply re-produce this by reject a promise without catch error in your browser console: 

```js
const asyncWillFail = ()=> new Promise(function(res, rej) {setTimeout(()=>rej(), 1000)});
asyncWillFail();
```

If those error message really annoying you, pls try : https://stackoverflow.com/questions/28001722/how-to-catch-uncaught-exception-in-promise

@alianrock @JjieChen 
I just updated this comment with better explain(I thought) & link to solution.

**Comment by JjieChen** [comment]
可不可以在你的example里写下怎么解决这个错误。谢谢
