### ISSUE TITLE
关于promise reject的问题

### ISSUE THREAD

**Issue by JjieChen** [kpaxqin/redux-action-tools#3]
你好，你的Example没有看到reject的处理，我只能自己测试了一下。如果promise reject的话，会报Uncaught (in promise) Error: Ops, async operation failed。这个已经有人提问过了。我看完你的回答。是不是这样理解，在createAsyncAction的时候promiseCreator就带有catch。如这样：
const test =  createAsyncAction('TEST', function(dispatch, getState) {
  return (new Promise(function(resolve, reject) {
    setTimeout(() => {
      reject(new Error('Ops, async operation failed'));
    }, 1000)
  })).catch(e=>{})
})

如果是这样写的话，的确不会有Uncaught的错误，但是会引发另外的问题，这样是不会发出TEST_FAILED的action的。只会发出TEST_COMPLETED 的action。
所以不知道是不是我的理解有误，希望你的Example能写下关于reject的时候怎么处理。

**Comment by kpaxqin** [comment]
这个问题的本质是uncaught promise的error如何处理，而这并不在redux-action-tools能解决的范围，任何未被catch的promise error都会打印上述错误，在浏览器中执行以下代码即可重现(注意并不会触发window.onerror)

```js
window.onerror = ()=>{console.log('window onerror called!')};
const asyncWillFail = ()=> new Promise(function(res, rej) {setTimeout(()=>rej(), 1000)});  
asyncWillFail()
```

站在redux-action-tools的角度，为了支持`chainable action`，返回一个能够忠实反映异步状态的promise是必须的，对这个promise如何处理应该交给用户，而多数情况下用户不会去处理(这是合理的)， 因此我暂时没看到有办法避免这个错误信息。

> react和redux的活跃贡献者acdlite写的redux-promise同样有这个问题：https://github.com/acdlite/redux-promise/blob/master/src/index.js

需要注意的是：这个error并不会导致任何实际的问题，主线程不会因此停止或挂起。甚至不会触发window.onerror，即使不去处理它也不会有什么问题。

如果一定要避免这个error message，请查阅 [How to catch uncaught exception in Promise](https://stackoverflow.com/questions/28001722/how-to-catch-uncaught-exception-in-promise) 相关资料
